### ISSUE TITLE
rempve vc14 feature

### ISSUE THREAD

**Issue by beckermr** [conda-forge/tiledb-py-feedstock#102]
This feedstock is using a vc14 feature. That is a very outdated way of doing things and is removed by our repodata patching. We should remove it from the build.

**Comment by ihnorton** [comment]
Hi @beckermr, thanks for pointing this out. Added in #102, will merge after CI.

**Comment by ihnorton** [comment]
Fixed in https://github.com/conda-forge/tiledb-py-feedstock/commit/876caf8fb38cf831fe83be849b4ec7ad27cd01c9

**Comment by beckermr** [comment]
Thank you for fixing! Cheers!
