### ISSUE TITLE
2 of 4 win-64 builds of 0.20.0 spuriously failed

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/tiledb-py-feedstock#166]
After PR #165 was merged, 2 of the 4 win-64 builds on the merge commit d2d6feb9d2dd1dbe15ba286d27479ae2f810b493 failed to upload binaries because of a spurious network error when downloading miniforge

* [0.20.0 binaries available](https://anaconda.org/conda-forge/tiledb-py/files?version=0.20.0) - note only 2 win-64, while 4 for all the other platforms (for building against multiple numpy builds)
* [failed build against numpy 1.20](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=644827&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=ab3c72cc-d8b1-58f6-4306-ed5ab2055114)
* [failed build against numpy 1.23](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=644827&view=logs&j=00f5923e-fdef-5026-5091-0d5a0b3d5a2c&t=e9dd1b43-2c40-568e-7b7b-f7856f59e5ed)

The easiest fix would be to restart these 2 failed builds using the Azure UI. However, it's been my experience that conda-forge maintainers often don't have the required permissions to do this. If that's the case, pushing a single dummy commit (`--allow-empty`) directly to the main branch will do the trick (no need to bother with a PR, since that would simply waste more CI time)

**Comment by ihnorton** [comment]
Pushed, thanks for the heads up!

**Comment by jdblischak** [comment]
Great. The 2 missing win-64 binaries were successfully built and uploaded

![image](https://user-images.githubusercontent.com/1608317/214333079-a44eb0de-92f8-46b9-85d7-0f87e72e153f.png)

**Comment by jdblischak** [comment]
Note that this round the build for [osx_64_numpy1.20python3.9.____cpython](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=646657&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=3770) failed, but this is inconsequential for the feedstock since its binary was already uploaded in the previous round of builds. However, unlike the win-64 jobs which failed due to network disconnection, this osx-64 job spuriously failed during the tests. Copy-pasting below in case it's informative:

```
=========================== short test summary info ============================
FAILED tiledb/tests/test_multi_index-hp.py::TestMultiIndexPropertySparse::test_multi_index_two_way_query[U] - hypothesis.errors.Flaky: Hypothesis test_multi_index_two_way_query(self=<tests.test_multi_index-hp.TestMultiIndexPropertySparse object at 0x13b3462b0>, order='U', sparse_array_1d='/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tiledb-disktestcasem4973udz/tmp35ucussj', ranges=[(2, 99)]) produces unreliable results: Falsified on the first call but did not on a subsequent one
Falsifying example: test_multi_index_two_way_query(
    ranges=[(2, 99)],
    self=<tests.test_multi_index-hp.TestMultiIndexPropertySparse object at 0x13b3462b0>,
    order='U',
    sparse_array_1d='/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tiledb-disktestcasem4973udz/tmp35ucussj',
)
Unreliable test timings! On an initial run, this test took 785.75ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 8.86 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

You can reproduce this example by temporarily adding @reproduce_failure('6.64.0', b'AAEDAAJ/AGMA') as a decorator on your test case
== 1 failed, 383 passed, 2 skipped, 7 xfailed, 1 xpassed in 102.18s (0:01:42) ==
```
