### ISSUE TITLE
Need to restart osx-64 build for Python 3.10 after spurious failure

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/tiledb-py-feedstock#176]
### Comment:

After PR #174 was merged yesterday, the [osx-64 build for 3.10](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=746404&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00) failed spuriously:

```
Falsifying example: test_multi_index_two_way_query(
    self=<tests.test_multi_index-hp.TestMultiIndexPropertySparse object at 0x13e43e3e0>,
    order='C',
    sparse_array_1d='/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tiledb-disktestcaseeb5n_8ei/tmp6wee58jn',
    ranges=[(-7, 1)],
)
Unreliable test timings! On an initial run, this test took 810.28ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 28.41 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

You can reproduce this example by temporarily adding @reproduce_failure('6.81.2', b'AAFwAQdyAAEA') as a decorator on your test case
== 1 failed, 383 passed, 1 skipped, 7 xfailed, 1 xpassed in 105.59s (0:01:45) ==
```

@conda-forge/tiledb-py could one of the maintainers please restart the failed job? You should be able to do this directly in the GitHub UI: https://github.com/conda-forge/tiledb-py-feedstock/runs/15114266511

**Comment by Shelnutt2** [comment]
I've restarted it and will monitor for success.

**Comment by jdblischak** [comment]
The [build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=746978&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=20c71c51-4b27-578b-485d-06ade2de1d00) succeeded and the binary was [uploaded](https://anaconda.org/conda-forge/tiledb-py/files?version=0.22.0)

![image](https://github.com/conda-forge/tiledb-py-feedstock/assets/1608317/8597d589-d06f-49ff-a5a0-2e0bd2a45abf)
